#!/usr/bin/env python
# -*- coding: utf-8 -*-

""" metadata.py

Metadata for passage comprehension results
"""
__author__ = 'Scott Burns <scott.s.burns@vanderbilt.edu>'
__copyright__ = 'Copyright 2012 Vanderbilt University. All Rights Reserved'

CORRECT = [
('toads', 'compmon',  1),
('toads', 'factual',  2),
('toads', 'factual',  2),
('toads', 'factual',  1),
('toads', 'interpretation',  1),
('toads', 'interpretation',  3),
('toads', 'interpretation',  2),
('toads', 'process_strategy',  3),
('toads', 'critical_analysis',  2),
('sap', 'compmon',  1),
('sap', 'factual',  3),
('sap', 'factual',  2),
('sap', 'factual',  2),
('sap', 'interpretation',  1),
('sap', 'interpretation',  3),
('sap', 'interpretation',  1),
('sap', 'process_strategy',  3),
('sap', 'critical_analysis',  1),
('oct', 'compmon',  1),
('oct', 'factual',  2),
('oct', 'factual',  1),
('oct', 'interpretation',  2),
('oct', 'interpretation',  3),
('oct', 'interpretation',  2),
('oct', 'process_strategy',  3),
('scabs', 'compmon',  3),
('scabs', 'factual',  3),
('scabs', 'factual',  2),
('scabs', 'factual',  2),
('scabs', 'interpretation',  1),
('scabs', 'interpretation',  3),
('scabs', 'process_strategy',  1),
('scabs', 'process_strategy',  1),
('mustangs', 'compmon',  2),
('mustangs', 'factual',  2),
('mustangs', 'factual',  1),
('mustangs', 'factual',  3),
('mustangs', 'interpretation',  3),
('mustangs', 'interpretation',  3),
('mustangs', 'interpretation',  1),
('mustangs', 'process_strategy',  2),
('mustangs', 'critical_analysis',  2),
('hab', 'compmon',  1),
('hab', 'factual',  2),
('hab', 'factual',  3),
('hab', 'factual',  2),
('hab', 'interpretation',  1),
('hab', 'interpretation',  2),
('hab', 'interpretation',  1),
('hab', 'process_strategy',  1),
('hab', 'critical_analysis',  3),
('moths', 'compmon',  1),
('moths', 'factual',  3),
('moths', 'factual',  1),
('moths', 'factual',  3),
('moths', 'interpretation',  3),
('moths', 'interpretation',  2),
('moths', 'interpretation',  1),
('moths', 'critical_analysis',  1),
('moths', 'process_strategy',  2),
('wbf', 'compmon',  2),
('wbf', 'factual',  3),
('wbf', 'factual',  1),
('wbf', 'factual',  2),
('wbf', 'interpretation',  2),
('wbf', 'interpretation',  1),
('wbf', 'interpretation',  3),
('wbf', 'process_strategy',  2),
('wbf', 'critical_analysis',  1),
('wbf', 'process_strategy',  1),
('crocs', 'compmon',  3),
('crocs', 'factual',  2),
('crocs', 'factual',  3),
('crocs', 'factual',  1),
('crocs', 'interpretation',  1),
('crocs', 'interpretation',  3),
('crocs', 'interpretation',  2),
('crocs', 'process_strategy',  3),
('crocs', 'process_strategy',  2),
('igloos', 'compmon',  2),
('igloos', 'factual',  3),
('igloos', 'factual',  2),
('igloos', 'factual',  1),
('igloos', 'interpretation',  3),
('igloos', 'interpretation',  2),
('igloos', 'interpretation',  2),
('igloos', 'process_strategy',  2),
('igloos', 'critical_analysis',  1),
('bugs', 'compmon',  2),
('bugs', 'factual',  3),
('bugs', 'factual',  1),
('bugs', 'factual',  3),
('bugs', 'interpretation',  3),
('bugs', 'interpretation',  1),
('bugs', 'interpretation',  1),
('bugs', 'process_strategy',  2),
('bugs', 'process_strategy',  3),
('deserts', 'compmon',  1),
('deserts', 'factual',  2),
('deserts', 'factual',  3),
('deserts', 'factual',  1),
('deserts', 'interpretation',  3),
('deserts', 'interpretation',  3),
('deserts', 'interpretation',  2),
('deserts', 'interpretation',  2),
('deserts', 'process_strategy',  1),
('deserts', 'critical_analysis',  2),
('deserts', 'critical_analysis',  3)]

MANIP = {1: {'sap': 'v', 'scabs': 'n', 'hab': 'c', 'wbf': 'd', 'crocs': 'f', 'igloos': 's'},  # 'A'
         2: {'sap': 'v', 'scabs': 'n', 'hab': 'c', 'wbf': 'd', 'crocs': 'f', 'bugs': 's'},  # 'B'
         3: {'sap': 'v', 'scabs': 'n', 'mustangs': 'c', 'wbf': 'd', 'crocs': 'f', 'bugs': 's'},  # 'C'
         4: {'sap': 'v', 'scabs': 'f', 'mustangs': 'c', 'wbf': 'd', 'crocs': 'n', 'bugs': 's'},  # 'D'
         5: {'sap': 'v', 'scabs': 'f', 'mustangs': 'c', 'moths': 'd', 'crocs': 'n', 'bugs': 's'},  # 'E'
         6: {'oct': 'v', 'scabs': 'f', 'mustangs': 'c', 'moths': 'd', 'crocs': 'n', 'bugs': 's'},  # 'F'
         7: {'oct': 'v', 'scabs': 'f', 'mustangs': 'c', 'moths': 'd', 'crocs': 'n', 'igloos': 's'},  # 'G'
         8: {'oct': 'v', 'scabs': 'f', 'hab': 'c', 'moths': 'd', 'crocs': 'n', 'igloos': 's'},  # 'H'
         9: {'oct': 'v', 'scabs': 'n', 'hab': 'c', 'moths': 'd', 'crocs': 'f', 'igloos': 's'},  # 'I'
         10: {'oct': 'v', 'scabs': 'n', 'hab': 'c', 'wbf': 'd', 'crocs': 'f', 'igloos': 's'}  # 'J'
         }
